### PR TITLE
Adding the ability to create a continuable with gen-run

### PR DESCRIPTION
**Pull request by chuckjaz**
This allows you to create a classic callback API implemented with a generator as explained in the modified documentation.

### CODE REVIEW

**Comment by creationix** [comment]
I originally had an interface like this in gen-run, but took it out for a few reasons:
1. It doubles the size of the library.
2. It encourages people to consume gen-run based continuables instead of plain generators using yield*. (only the outer generator needs gen-run, all inside ones don't need wrapping)
3. It's trivial to manually wrap a gen-run call inside a function.

``` js
function concatFiles(path1, path2, callback) {
  // Allow this function to run as either callback-last or return-continuable styles.
  if (!callback) return concatFiles.bind(path1, path2);
  genRun(function * () {
    try {
      var data1 = yield fs.readFile(path1, "utf8");
      var data2 = yield fs.readFile(path2, "utf8");
      var result = data1 + data2;
    } catch (err) {
      return callback(err);
    }
    callback(null, result);
  });
}
```

Ok, maybe it's not that trivial.  I'll think about this one for a bit.

**Comment by creationix** [comment]
So assuming the library accecpted a callback, the example could be written as?

``` js
genRun(function *() {
  return yield fs.readFile(path1, "utf8") + yield fs.readFile(path2, "utf8");
}, function (err, result) {
  // handle error or result.
})
```

**Comment by creationix** [comment]
I can see value in accepting the callback, but I'm not sold on returning a continuable.  Once we accept callbacks, that can be done with:

``` js
var cont = genRun.bind(null, function *() { ... });
```

**Comment by chuckjaz** [comment]
The callback parameter is certainly the meat of the change. I like the `bind()` example.

I was also uncomfortable with the size of the change. I gave it a few tries to reduce it but the `try`..`catch` block was unavoidable. However, looking at this again, I put the handler at too low a level.

I will take another run at this change tonight with just a callback, dropping the `wrap()` method. I believe I fix too low level catch problem and can get it smaller with a generalized version of the first function.

**Comment by chuckjaz** [comment]
I removed `wrap()` as well as provided a smaller version of the change. The smaller version, however, requires generator syntax where the previous version did not. Because of that I left the longer version in the history.

**Comment by creationix** [comment]
Interesting use of generator delegation.  I do worry about the performance impact of nesting a second generator though.  Would a micro-benchmark be useful here you think?

**Comment by chuckjaz** [comment]
Using the following,

``` js
var run = require('../gen-run');

function empty(callback) {
  callback(null, null);
}

function test(name, generator, callback) {
  console.log('Starting: ' + name);

  var start = new Date();
  for (var i = 0; i < 1000000; i++) {
    run(generator, callback);
  }
  var done = new Date();

  console.log(name + ': ' + (done - start));
}

test('Empty, no callback', function *() {
  yield empty;
});

test('Empty, callback', function *() {
  yield empty;
}, function () { })
```

The longer version is might be slightly slower than not having a callback,

Starting: Empty, no callback
Empty, no callback: 1968
Starting: Empty, callback
Empty, callback: 1982

The shorter version is about 4x slower

Starting: Empty, no callback
Empty, no callback: 2861
Starting: Empty, callback
Empty, callback: 13496

**Comment by creationix** [comment]
I ended up writing the patch the way I wanted it written, but I'll happily take a pull request for your additional unit tests.  Also I've integrated your README changes.  Thanks for the support!

**Comment by chuckjaz** [comment]
I like the format change. I will think about more unit tests.

**Pull request closed without merging**
